--name: fill-tables
INSERT INTO `config` (`lastmatch`,`refresh`,`stage`) VALUES (1,0,1);
INSERT INTO `users` (`id`,`firstname`,`lastname`,`password`,`email`,`score`,`champion`,`champchange`,`position`,`positionbefore`,`malus`,`bonus`,`ngoodscores`,`ngoodwinner`) VALUES (1,'Gilles','Dejeneffe','9dc08e4033827c93f48cabc2f61e3f9817b51a7f1bcfa513a7537dcbc5d162e7','test@test.com',0,2,0,1,1,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (1,'Qatar',0,'A1',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (2,'b',0,'A2',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (3,'c',0,'A3',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (4,'d',0,'A4',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (5,'e',0,'B1',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (6,'f',0,'B2',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (7,'g',0,'B3',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (8,'h',0,'B4',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (9,'i',0,'C1',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (10,'j',0,'C2',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (11,'k',0,'C3',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (12,'l',0,'C4',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (13,'m',0,'D1',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (14,'n',0,'D2',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (15,'o',0,'D3',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (16,'p',0,'D4',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (17,'q',0,'E1',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (18,'r',0,'E2',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (19,'s',0,'E3',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (20,'t',0,'E4',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (21,'u',0,'F1',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (22,'v',0,'F2',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (23,'w',0,'F3',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (24,'x',0,'F4',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (25,'y',0,'G1',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (26,'z',0,'G2',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (27,'aa',0,'G3',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (28,'bb',0,'G4',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (29,'cc',0,'H1',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (30,'dd',0,'H2',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (31,'ee',0,'H3',0,0,0,0,0,0);
INSERT INTO `teams` (`id`,`name`,`active`,`groupid`,`point`,`win`,`drawn`,`lose`,`goalfor`,`goalagainst`) VALUES (32,'ff',0,'H4',0,0,0,0,0,0);
INSERT INTO `stats` (`nombrebut`,`goodprono`,`goodwinner`,`redcard`,`yellowcard`) VALUES (0,0,0,0,0);
INSERT INTO `stage` (`id`,`name`,`active`) VALUES (1,'Groupe Stage 1',0);
INSERT INTO `stage` (`id`,`name`,`active`) VALUES (2,'Groupe Stage 2',0);
INSERT INTO `stage` (`id`,`name`,`active`) VALUES (3,'Groupe Stage 3',0);
INSERT INTO `stage` (`id`,`name`,`active`) VALUES (4,'Round of 16',0);
INSERT INTO `stage` (`id`,`name`,`active`) VALUES (5,'Quarter-finals',0);
INSERT INTO `stage` (`id`,`name`,`active`) VALUES (6,'Semi-finals',0);
INSERT INTO `stage` (`id`,`name`,`active`) VALUES (7,'Little Final',0);
INSERT INTO `stage` (`id`,`name`,`active`) VALUES (8,'Final',0);
INSERT INTO `matches` (`id`,`stage`,`date`,`teama`,`scorea`,`pena`,`teamb`,`scoreb`,`penb`,`stadium`) VALUES (1,1,'2022-11-21 13:00:00',1,0,0,2,0,0,2);
INSERT INTO `matches` (`id`,`stage`,`date`,`teama`,`scorea`,`pena`,`teamb`,`scoreb`,`penb`,`stadium`) VALUES (2,1,'2022-11-21 16:00:00',5,0,0,6,0,0,4);
INSERT INTO `matches` (`id`,`stage`,`date`,`teama`,`scorea`,`pena`,`teamb`,`scoreb`,`penb`,`stadium`) VALUES (3,1,'2022-11-21 19:00:00',3,0,0,4,0,0,7);
INSERT INTO `matches` (`id`,`stage`,`date`,`teama`,`scorea`,`pena`,`teamb`,`scoreb`,`penb`,`stadium`) VALUES (4,1,'2022-11-21 22:00:00',7,0,0,8,0,0,6);
INSERT INTO `matches` (`id`,`stage`,`date`,`teama`,`scorea`,`pena`,`teamb`,`scoreb`,`penb`,`stadium`) VALUES (5,1,'2022-11-22 13:00:00',15,0,0,16,0,0,8);
INSERT INTO `matches` (`id`,`stage`,`date`,`teama`,`scorea`,`pena`,`teamb`,`scoreb`,`penb`,`stadium`) VALUES (6,1,'2022-11-22 16:00:00',13,0,0,14,0,0,5);
INSERT INTO `matches` (`id`,`stage`,`date`,`teama`,`scorea`,`pena`,`teamb`,`scoreb`,`penb`,`stadium`) VALUES (7,1,'2022-11-22 19:00:00',11,0,0,12,0,0,3);
INSERT INTO `matches` (`id`,`stage`,`date`,`teama`,`scorea`,`pena`,`teamb`,`scoreb`,`penb`,`stadium`) VALUES (8,1,'2022-11-22 22:00:00',9,0,0,10,0,0,1);
INSERT INTO `stadium` (`id`,`name`) VALUES (1,'Lusail Iconic Stadium');
INSERT INTO `stadium` (`id`,`name`) VALUES (2,'Al Bayt Stadium');
INSERT INTO `stadium` (`id`,`name`) VALUES (3,'Stadium 974');
INSERT INTO `stadium` (`id`,`name`) VALUES (4,'Al Thumama Stadium');
INSERT INTO `stadium` (`id`,`name`) VALUES (5,'Education City Stadium');
INSERT INTO `stadium` (`id`,`name`) VALUES (6,'Ahmed bin Ali Stadium');
INSERT INTO `stadium` (`id`,`name`) VALUES (7,'Khalifa International Stadium');
INSERT INTO `stadium` (`id`,`name`) VALUES (8,'Al Janoub Stadium');